### ISSUE TITLE
IDs for header tags

### ISSUE THREAD

**Issue by CodeMyst** [p0nce/commonmark-d#1]
is it possible to add IDs for header tags?

example, this:

```md
# title
```

would get parsed to:

```html
<h1 id="title">title</h1>
```

this is useful for linking to various section of the text inside the same page.

**Comment by p0nce** [comment]
Well it's not in CommonMark and seem to generate a lot of discussions, and also quite tricky to implement (I have not written the original MD4C). I suggest you use HTML tags for example 
```html
<a name="my-anchor"/>
```

**Comment by CodeMyst** [comment]
Ah I see, that makes sense. I'll just use HTML tags then.
