### ISSUE TITLE
[Feature request] Update the port to include wikilinks

### ISSUE THREAD

**Issue by bachmeil** [p0nce/commonmark-d#2]
Wikilinks were added to MD4C after you completed this port. Is there any chance adding them in the future?

References:

- [Merged PR](https://github.com/mity/md4c/pull/92)
- [Original feature request](https://github.com/mity/md4c/issues/90)

**Comment by p0nce** [comment]
I'm not going to do it, but if someone port this to the fork and provide a nice-looking PR that works without taking my time, I will merge. https://github.com/mity/md4c/pull/92/commits/01a8533775f5f5ea8873e61c799ad4b4549981b7

**Comment by p0nce** [comment]
It would be better to use ImportC eventually since the CommonMark specification is evolving and we only support 0.29, the test suite of 0.28, 0.30, 0.31 doesn't pass.
So this package makes little sense in the long term, being a fork.
